### ISSUE TITLE
最近的更新是不是只能用在10.15上啊，我这边没法启动，可能是什么原因呢

### ISSUE THREAD

**Issue by elsfsb** [fangf2018/ASRock-Z370-Gaming-ITX-ac-hackintosh#8]
主板的型号和这个一致，cpu是8500的，之前下载的配置文件直接复制就能用，换了virtualsmc以后的配置文件直接复制没法启动，不知道什么地方出问题了，是不是10.14.6不支持啊，还是我更新到10.15以后就好了？

**Comment by GeekAudio** [comment]
上个图比描述更有用
